FROM python:3.10-alpine

# Set the working directory in the container
WORKDIR /app

COPY . /app/




# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Create a new user 'doc'
RUN adduser -D doc

# Change to 'doc' user
USER doc

# Run the application
CMD ["python", "sample_1/main.py"]

