FROM python:3.10-alpine

WORKDIR /app

COPY . /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run main.py when the container launches
CMD ["pytest"]
